### ISSUE TITLE
何时发布下一个版本？

### ISSUE THREAD

**Issue by xyy94813** [AMap-Web/amap-jsapi-types#27]
PolylineEditor 目录名大小写错误这么严重的问题合并了那么久何时进行下一版本发布？

-----------

这个项目的目标到底是什么？？？

amap-js-api 的类型说明五花八门

- [DefinitelyTyped/types/amap-js-api](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/amap-js-api)
- [DefinitelyTyped/types/amap-js-sdk](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/amap-js-sdk)
- [@uiw/react-amap-types](https://yarnpkg.com/package?q=%40uiw%2Freact-amap-types&name=%40uiw%2Freact-amap-types)

作为官方社区维护的开源项目，并且在官方文档推荐的产品，是不是应该稍微提高点质量？？？？？
如果时间不足是不是应该考虑下吸纳更多的社区开发人员进行管理？？

**Comment by lbs-amap** [comment]
计划本周发布更新一个版本

**Comment by lbs-amap** [comment]
已发布最新版本，修复报错问题

**Comment by xyy94813** [comment]
兄弟你基于哪个分支发的版？
https://www.npmjs.com/package/@amap/amap-jsapi-types?activeTab=code

https://www.npmjs.com/package/@amap/amap-jsapi-types/v/0.0.14?activeTab=code

```ts
import { _PolylineEditor } from "./plugins/PolylIneEditor";
```
发版失败了

**Comment by lbs-amap** [comment]
感谢反馈，已经修改并重新发布版本
